### ISSUE TITLE
Can you provide an option to swap the size of the primary and secondary colors?

### ISSUE THREAD

**Issue by zyowo** [lsoft/ColorTabs2019#1]
![image](https://user-images.githubusercontent.com/30146416/180387248-f754f513-f3c2-45b1-9f34-3ae26879eac9.png)

Thank you so much for bringing my much needed color tab feature to 2019. From the screenshot, you can see that different assemblies have differentiated the code, so the primary color is not necessary, and the secondary color is more useful.

**Comment by lsoft** [comment]
@zyowo hi! I was on vacantion. If you want to disable primary color, you can easily do that, you need to put something like [this](https://github.com/lsoft/ColorTabs2019/blob/main/ColorTabs2019/Backgrounder.cs#L161) [here](https://github.com/lsoft/ColorTabs2019/blob/main/ColorTabs2019/Backgrounder.cs#L146)

You will need a new option in `General.Instance`. Feel free to create a PR!
